Repository Flea00012/GroupProject-SDArepo, pull requests merged in 2020-11, with the labels that each got.

#15 Implementation of basic Navbar with testing
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/assignments/AssignmentsPage.js
  frontend/src/components/courses/CoursePage.js
  frontend/src/components/layout/Navbar.js
  frontend/src/components/layout/__test__/Navbar.test.js
  frontend/src/components/lectures/LecturesPage.js
  frontend/src/components/students/StudentsPage.js
Labels: enhancement

#24 Lf 10 student entity (CRUD MVC) with Mockito tests
  src/main/java/se/kth/sda/skeleton/student/Student.java
  src/main/java/se/kth/sda/skeleton/student/StudentController.java
  src/main/java/se/kth/sda/skeleton/student/StudentRepository.java
  src/main/java/se/kth/sda/skeleton/student/StudentService.java
  src/main/resources/application.properties
  src/test/java/se/kth/sda/skeleton/student/StudentControllerTest.java
  src/test/java/se/kth/sda/skeleton/student/StudentServiceTest.java
Labels: enhancement

#26 Lf 10 student entity - updated documentation for the student entity and MVC
  src/main/java/se/kth/sda/skeleton/student/Student.java
  src/main/java/se/kth/sda/skeleton/student/StudentController.java
  src/main/java/se/kth/sda/skeleton/student/StudentService.java
Labels: documentation

#27 Lf 10 student entity - testing
  src/test/java/se/kth/sda/skeleton/student/StudentServiceTest.java
Labels: unit tests

#30 made the videos page and added videos
  frontend/src/App.js
  frontend/src/components/layout/Navbar.js
  frontend/src/components/students/StudentsPage.js
  frontend/src/components/videos/Video.jsx
  frontend/src/components/videos/VideosPage.jsx
  frontend/src/resources/information.json
Labels: enhancement

#38 updated Courses
  src/main/java/se/kth/sda/skeleton/Course/Course.java
  src/main/java/se/kth/sda/skeleton/Course/CourseController.java
  src/main/java/se/kth/sda/skeleton/Course/CourseRepository.java
  src/main/java/se/kth/sda/skeleton/Course/CourseService.java
  src/main/java/se/kth/sda/skeleton/assignments/AssignmentController.java
Labels: enhancement

#41 Lf 31 student jsx
  frontend/src/App.js
  frontend/src/components/students/Student.jsx
  frontend/src/components/students/StudentCreateForm.jsx
  frontend/src/components/students/Students.jsx
  frontend/src/components/students/StudentsPage.js
  frontend/src/components/videos/VideosPage.jsx
Labels: enhancement

#43 Lf 31 student jsx
  frontend/src/components/students/StudentCard.jsx
  frontend/src/components/students/Students.jsx
  frontend/src/components/students/StudentsPage.js
  src/main/resources/application.properties
Labels: enhancement

#45 Pm mergeconflict
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/api/AssignmentsApi.js
  frontend/src/components/assignments/AssignmentsPage.js
  frontend/src/components/assignments/AssignmentsView.js
Labels: bug

#46 Student page
  frontend/src/App.css
  frontend/src/components/students/StudentsPage.js
Labels: enhancement

#47 Lf 31 student jsx
  frontend/src/components/students/Student.jsx
  frontend/src/components/students/StudentCard.jsx
  frontend/src/components/students/Students.jsx
Labels: enhancement

#48 Lf 31 student jsx
  frontend/src/components/students/Students.jsx
  frontend/src/components/students/StudentsPage.js
Labels: bug, enhancement
