Repository Flea00012/GroupProject-SDArepo, pull requests merged in 2020-12, with the labels that each got.

#61 Lf 52 authenticate
  src/main/java/se/kth/sda/skeleton/config/WebSecurityConfig.java
Labels: enhancement

#74 Lf 62 crud video upload
  frontend/package.json
  frontend/src/components/videos/Uploader.jsx
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
  frontend/src/components/videos/Videos.jsx
  frontend/src/components/videos/VideosPage.jsx
  src/main/java/se/kth/sda/skeleton/video/Video.java
  src/main/java/se/kth/sda/skeleton/video/VideoController.java
  src/main/java/se/kth/sda/skeleton/video/VideoRepository.java
  src/main/java/se/kth/sda/skeleton/video/VideoService.java
  src/main/resources/application.properties
  src/test/java/se/kth/sda/skeleton/video/VideoServiceTest.java
Labels: bug, enhancement

#75 Lf 62 crud video upload
  frontend/src/components/courses/Course.js
  frontend/src/components/videos/VideoCard.jsx
Labels: enhancement

#83 Lf 62 crud video upload
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
  frontend/src/components/videos/Videos.jsx
Labels: enhancement

#91 Lf 87 student and assignment
  frontend/src/components/videos/VideoCard.jsx
  src/main/resources/application.properties
Labels: bug

#104 Lf 99 user and answers mapped
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignment.java
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentController.java
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentRepository.java
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentService.java
  src/main/java/se/kth/sda/skeleton/user/User.java
Labels: enhancement

#106 Lf 97 video material UI
  frontend/src/CSS/styles.css
  frontend/src/CSS/videos.css
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
  frontend/src/components/videos/Videos.jsx
Labels: design

#107 Lf 97 video material UI
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
  frontend/src/components/videos/Videos.jsx
  frontend/src/components/videos/VideosPage.jsx
Labels: enhancement

#109 created event onMouseOver for the courses card
  frontend/src/components/courses/Course.js
Labels: enhancement

#114 Added Accordian for Answered Assignment
  frontend/src/api/AnsweredAssignmentsApi.jsx
  frontend/src/components/accordian/AccordianForAssignment.jsx
  frontend/src/components/answeredAssignments/AssignmentSubmitted.jsx
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentController.java
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentRepository.java
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentService.java
Labels: enhancement

#118 Lf 111 redirect user assignments
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
Labels: enhancement

#123 Lf 111 redirect user assignments
  frontend/src/components/assignments/AssignmentPageUpdation.jsx
  frontend/src/components/assignments/AssignmentsPage.js
Labels: bug

#127 Lf 125 calendar api
  frontend/package.json
  frontend/src/App.js
  frontend/src/CSS/scheduler.css
  frontend/src/components/home/HomePage.js
  frontend/src/components/layout/Navbar.js
  frontend/src/components/scheduler/Scheduler.jsx
  frontend/src/components/scheduler/SchedulerPage.jsx
Labels: design, enhancement

#136 Lf 125 calendar api
  frontend/src/components/scheduler/Scheduler.jsx
Labels: bug

#137 Lf xx m land ai
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/Videos.jsx
  src/main/resources/application.properties
Labels: bug, design

#142 Lf xx sentiment ml
  frontend/package.json
  frontend/src/components/chat/forum/Forum.jsx
  frontend/src/components/sentiment/Sentiment.js
  frontend/src/resources/trainingdata.json
Labels: enhancement

#153 corrected the deletion of Sentiment.js
  frontend/src/components/sentiment/Sentiment.js
Labels: bug

#168 Lf xx sentiment ml
  frontend/package.json
  frontend/src/components/chartplots/BarChartPosNeg.jsx
  frontend/src/components/chartplots/ChartsPage.jsx
  frontend/src/components/chartplots/RadarChart.jsx
  frontend/src/components/sentiment/Sentiment.js
  frontend/src/components/videos/VideosPage.jsx
Labels: enhancement

#183 Lf 143 mockito videos
  build.gradle
  src/main/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentController.java
  src/main/java/se/kth/sda/skeleton/course/CourseController.java
  src/test/java/se/kth/sda/skeleton/SkeletonApplicationTests.java
  src/test/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentControllerTest.java
  src/test/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentRestTest.java
  src/test/java/se/kth/sda/skeleton/answeredAssignments/AnsweredAssignmentServiceTest.java
  src/test/java/se/kth/sda/skeleton/assignments/AssignmentControllerTest.java
  src/test/java/se/kth/sda/skeleton/comment/CommentControllerTest.java
  src/test/java/se/kth/sda/skeleton/course/CourseControllerTest.java
  src/test/java/se/kth/sda/skeleton/question/QuestionControllerTest.java
  src/test/java/se/kth/sda/skeleton/question/QuestionServiceTest.java
  src/test/java/se/kth/sda/skeleton/video/VideoControllerTest.java
  src/test/java/se/kth/sda/skeleton/video/VideoServiceTest.java
  src/test/java/se/kth/sda/skeleton/video/VideosRestTest.java
Labels: unit tests

#204 Lf 186 rechart sentiment
  frontend/src/CSS/sentimentPlots.css
  frontend/src/CSS/styles.css
  frontend/src/components/chartplots/ChartPlots.jsx
  frontend/src/components/chartplots/ChartsPage.jsx
  frontend/src/components/chartplots/ScatterPlot.jsx
  frontend/src/components/chat/forum/Forum.jsx
  frontend/src/components/sentiment/Sentiment.js
  frontend/src/components/students/StudentsPage.jsx
  frontend/src/resources/trainingdata.json
Labels: enhancement

#206 updated the CSS and styling for the Sentiment analysis and plots
  frontend/src/CSS/sentimentPlots.css
  frontend/src/CSS/studentpage.css
  frontend/src/components/chartplots/ChartPlots.jsx
  frontend/src/components/students/StudentsPage.jsx
Labels: enhancement

#210 Create LICENSE
  LICENSE
Labels: documentation

#215 Lf 205 sentiment refactor
  frontend/src/App.js
  frontend/src/components/chartplots/BarChartPosNeg.jsx
  frontend/src/components/chartplots/ChartPlots.jsx
  frontend/src/components/chartplots/RadarChart.jsx
  frontend/src/components/chartplots/ScatterPlot.jsx
  frontend/src/components/layout/Navbar.js
  frontend/src/components/sentiment/Sentiment.js
  frontend/src/components/students/SentimentPage.jsx
Labels: code clean up

#220 Lf 205 sentiment refactor
  frontend/src/components/chartplots/ScatterPlot.jsx
  frontend/src/components/courses/Course.js
  frontend/src/components/courses/CourseCard.js
  frontend/src/components/courses/CourseDetailsPage.js
  frontend/src/components/courses/CourseForm.js
  frontend/src/components/courses/CoursePage.js
  frontend/src/components/courses/CourseUpdateForm.js
  frontend/src/components/courses/CoursesList.js
  frontend/src/components/home/HomePage.js
  frontend/src/components/layout/Navbar.js
  frontend/src/components/posts/PostsPage.js
  frontend/src/components/resourse/ResoursePage.js
  frontend/src/components/scheduler/Scheduler.jsx
  frontend/src/components/scheduler/SchedulerPage.jsx
  frontend/src/components/sentiment/Sentiment.js
  frontend/src/components/sentiment/SentimentPage.jsx
  frontend/src/components/star/RatingIcon.jsx
  frontend/src/components/star/StarIcon.jsx
  frontend/src/components/star/StarRating.jsx
  frontend/src/components/videos/Uploader.jsx
  frontend/src/components/videos/Video.jsx
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/components/videos/VideoUploadForm.jsx
  frontend/src/components/videos/Videos.jsx
  frontend/src/components/videos/VideosPage.jsx
Labels: code clean up, documentation

#222 Lf 205 sentiment refactor
  frontend/src/App.js
  frontend/src/api/AnsweredAssignmentsApi.jsx
  frontend/src/api/Api.js
  frontend/src/api/AssignmentsApi.js
  frontend/src/api/AuthApi.js
  frontend/src/api/CommentsApi.jsx
  frontend/src/api/CoursesApi.js
  frontend/src/api/LecturesApi.jsx
  frontend/src/api/QuestionsApi.js
  frontend/src/api/UserApi.jsx
  frontend/src/components/accordian/AccordianForAssignment.jsx
  frontend/src/components/answeredAssignments/AnsweredAssignmentForm.jsx
  frontend/src/components/answeredAssignments/AnsweredAssignmentPage.jsx
  frontend/src/components/answeredAssignments/AssignmentGrade.jsx
  frontend/src/components/answeredAssignments/AssignmentSubmitted.jsx
  frontend/src/components/answeredAssignments/DisplaySubmittedAssignment.jsx
  frontend/src/components/assignments/AssignmentPageUpdation.jsx
  frontend/src/components/assignments/AssignmentsPage.js
  frontend/src/components/assignments/AssignmentsView.js
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/chartplots/ScatterPlot.jsx
  frontend/src/components/chat/chatComp/Chat.js
  frontend/src/components/chat/chatComp/ChatInput.js
  frontend/src/components/chat/chatComp/ChatMessage.js
  frontend/src/components/chat/chatComp/ChatPage.js
  frontend/src/components/chat/forum/CommentCard.jsx
  frontend/src/components/chat/forum/CommentForm.jsx
  frontend/src/components/chat/forum/Forum.jsx
  frontend/src/components/chat/forum/QuestionForm.jsx
  frontend/src/components/chat/forum/ShowComments.jsx
  frontend/src/components/chat/forum/ShowQuestions.jsx
Labels: code clean up, documentation

#226 updated the anchor links to react-router-dom Links for use on Firebase
  frontend/src/components/layout/Navbar.js
  frontend/src/components/videos/VideoCard.jsx
  frontend/src/css/_variable.css
  frontend/src/css/assignment.css
  frontend/src/css/chat.css
  frontend/src/css/course-details.css
  frontend/src/css/course.css
  frontend/src/css/homePage.css
  frontend/src/css/login.css
  frontend/src/css/loginPage.css
  frontend/src/css/resoursepage.css
  frontend/src/css/scheduler.css
  frontend/src/css/sentimentPlots.css
  frontend/src/css/starRating.css
  frontend/src/css/studentpage.css
  frontend/src/css/styles.css
  frontend/src/css/videos.css
Labels: bug

#227 Lf xx css responsive
  frontend/src/App.css
Labels: bug
